--
-- PostgreSQL database dump
--

-- Dumped from database version 12.8
-- Dumped by pg_dump version 12.8

-- Started on 2022-09-12 19:54:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 203 (class 1259 OID 1747317)
-- Name: cidade; Type: TABLE; Schema: public; Owner: md2net
--

CREATE TABLE public.cidade (
    id bigint NOT NULL,
    nome character varying(255) NOT NULL,
    estado_id bigint NOT NULL
);


ALTER TABLE public.cidade OWNER TO md2net;

--
-- TOC entry 202 (class 1259 OID 1747315)
-- Name: cidade_id_seq; Type: SEQUENCE; Schema: public; Owner: md2net
--

ALTER TABLE public.cidade ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cidade_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 1747324)
-- Name: cozinha; Type: TABLE; Schema: public; Owner: md2net
--

CREATE TABLE public.cozinha (
    id bigint NOT NULL,
    nome character varying(255)
);


ALTER TABLE public.cozinha OWNER TO md2net;

--
-- TOC entry 204 (class 1259 OID 1747322)
-- Name: cozinha_id_seq; Type: SEQUENCE; Schema: public; Owner: md2net
--

ALTER TABLE public.cozinha ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cozinha_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 1747331)
-- Name: estado; Type: TABLE; Schema: public; Owner: md2net
--

CREATE TABLE public.estado (
    id bigint NOT NULL,
    nome character varying(255) NOT NULL
);


ALTER TABLE public.estado OWNER TO md2net;

--
-- TOC entry 206 (class 1259 OID 1747329)
-- Name: estado_id_seq; Type: SEQUENCE; Schema: public; Owner: md2net
--

ALTER TABLE public.estado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 1747338)
-- Name: forma_pagamento; Type: TABLE; Schema: public; Owner: md2net
--

CREATE TABLE public.forma_pagamento (
    id bigint NOT NULL,
    descricao character varying(255) NOT NULL
);


ALTER TABLE public.forma_pagamento OWNER TO md2net;

--
-- TOC entry 208 (class 1259 OID 1747336)
-- Name: forma_pagamento_id_seq; Type: SEQUENCE; Schema: public; Owner: md2net
--

ALTER TABLE public.forma_pagamento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forma_pagamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 1747345)
-- Name: grupo; Type: TABLE; Schema: public; Owner: md2net
--

CREATE TABLE public.grupo (
    id bigint NOT NULL,
    nome character varying(255) NOT NULL
);


ALTER TABLE public.grupo OWNER TO md2net;

--
-- TOC entry 210 (class 1259 OID 1747343)
-- Name: grupo_id_seq; Type: SEQUENCE; Schema: public; Owner: md2net
--

ALTER TABLE public.grupo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grupo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 1747350)
-- Name: grupo_permissao; Type: TABLE; Schema: public; Owner: md2net
--

CREATE TABLE public.grupo_permissao (
    grupo_id bigint NOT NULL,
    permissao_id bigint NOT NULL
);


ALTER TABLE public.grupo_permissao OWNER TO md2net;

--
-- TOC entry 214 (class 1259 OID 1747355)
-- Name: permissao; Type: TABLE; Schema: public; Owner: md2net
--

CREATE TABLE public.permissao (
    id bigint NOT NULL,
    descricao character varying(255) NOT NULL,
    nome character varying(255) NOT NULL
);


ALTER TABLE public.permissao OWNER TO md2net;

--
-- TOC entry 213 (class 1259 OID 1747353)
-- Name: permissao_id_seq; Type: SEQUENCE; Schema: public; Owner: md2net
--

ALTER TABLE public.permissao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 1747365)
-- Name: produto; Type: TABLE; Schema: public; Owner: md2net
--

CREATE TABLE public.produto (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    descricao character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    preco numeric(19,2) NOT NULL,
    restaurante_id bigint NOT NULL
);


ALTER TABLE public.produto OWNER TO md2net;

--
-- TOC entry 215 (class 1259 OID 1747363)
-- Name: produto_id_seq; Type: SEQUENCE; Schema: public; Owner: md2net
--

ALTER TABLE public.produto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 1747375)
-- Name: restaurante; Type: TABLE; Schema: public; Owner: md2net
--

CREATE TABLE public.restaurante (
    id bigint NOT NULL,
    data_atualizacao timestamp without time zone NOT NULL,
    data_cadastro timestamp without time zone NOT NULL,
    endereco_bairro character varying(255),
    endereco_cep character varying(255),
    endereco_complemento character varying(255),
    endereco_logradouro character varying(255),
    endereco_numero character varying(255),
    nome character varying(255) NOT NULL,
    taxa_frete numeric(19,2) NOT NULL,
    cozinha_id bigint NOT NULL,
    endereco_cidade_id bigint
);


ALTER TABLE public.restaurante OWNER TO md2net;

--
-- TOC entry 219 (class 1259 OID 1747383)
-- Name: restaurante_forma_pagamento; Type: TABLE; Schema: public; Owner: md2net
--

CREATE TABLE public.restaurante_forma_pagamento (
    restaurante_id bigint NOT NULL,
    forma_pagamento_id bigint NOT NULL
);


ALTER TABLE public.restaurante_forma_pagamento OWNER TO md2net;

--
-- TOC entry 217 (class 1259 OID 1747373)
-- Name: restaurante_id_seq; Type: SEQUENCE; Schema: public; Owner: md2net
--

ALTER TABLE public.restaurante ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurante_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 1747388)
-- Name: usuario; Type: TABLE; Schema: public; Owner: md2net
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    data_cadastro timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    email character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    senha character varying(255) NOT NULL
);


ALTER TABLE public.usuario OWNER TO md2net;

--
-- TOC entry 222 (class 1259 OID 1747397)
-- Name: usuario_grupo; Type: TABLE; Schema: public; Owner: md2net
--

CREATE TABLE public.usuario_grupo (
    usuario_id bigint NOT NULL,
    grupo_id bigint NOT NULL
);


ALTER TABLE public.usuario_grupo OWNER TO md2net;

--
-- TOC entry 220 (class 1259 OID 1747386)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: md2net
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TOC entry 2932 (class 0 OID 0)
-- Dependencies: 202
-- Name: cidade_id_seq; Type: SEQUENCE SET; Schema: public; Owner: md2net
--

SELECT pg_catalog.setval('public.cidade_id_seq', 1, false);


--
-- TOC entry 2933 (class 0 OID 0)
-- Dependencies: 204
-- Name: cozinha_id_seq; Type: SEQUENCE SET; Schema: public; Owner: md2net
--

SELECT pg_catalog.setval('public.cozinha_id_seq', 1, false);


--
-- TOC entry 2934 (class 0 OID 0)
-- Dependencies: 206
-- Name: estado_id_seq; Type: SEQUENCE SET; Schema: public; Owner: md2net
--

SELECT pg_catalog.setval('public.estado_id_seq', 1, false);


--
-- TOC entry 2935 (class 0 OID 0)
-- Dependencies: 208
-- Name: forma_pagamento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: md2net
--

SELECT pg_catalog.setval('public.forma_pagamento_id_seq', 1, false);


--
-- TOC entry 2936 (class 0 OID 0)
-- Dependencies: 210
-- Name: grupo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: md2net
--

SELECT pg_catalog.setval('public.grupo_id_seq', 1, false);


--
-- TOC entry 2937 (class 0 OID 0)
-- Dependencies: 213
-- Name: permissao_id_seq; Type: SEQUENCE SET; Schema: public; Owner: md2net
--

SELECT pg_catalog.setval('public.permissao_id_seq', 1, false);


--
-- TOC entry 2938 (class 0 OID 0)
-- Dependencies: 215
-- Name: produto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: md2net
--

SELECT pg_catalog.setval('public.produto_id_seq', 9, true);


--
-- TOC entry 2939 (class 0 OID 0)
-- Dependencies: 217
-- Name: restaurante_id_seq; Type: SEQUENCE SET; Schema: public; Owner: md2net
--

SELECT pg_catalog.setval('public.restaurante_id_seq', 1, false);


--
-- TOC entry 2940 (class 0 OID 0)
-- Dependencies: 220
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: md2net
--

SELECT pg_catalog.setval('public.usuario_id_seq', 1, false);


--
-- TOC entry 2753 (class 2606 OID 1747321)
-- Name: cidade cidade_pkey; Type: CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.cidade
    ADD CONSTRAINT cidade_pkey PRIMARY KEY (id);


--
-- TOC entry 2755 (class 2606 OID 1747328)
-- Name: cozinha cozinha_pkey; Type: CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.cozinha
    ADD CONSTRAINT cozinha_pkey PRIMARY KEY (id);


--
-- TOC entry 2757 (class 2606 OID 1747335)
-- Name: estado estado_pkey; Type: CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.estado
    ADD CONSTRAINT estado_pkey PRIMARY KEY (id);


--
-- TOC entry 2759 (class 2606 OID 1747342)
-- Name: forma_pagamento forma_pagamento_pkey; Type: CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.forma_pagamento
    ADD CONSTRAINT forma_pagamento_pkey PRIMARY KEY (id);


--
-- TOC entry 2761 (class 2606 OID 1747349)
-- Name: grupo grupo_pkey; Type: CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.grupo
    ADD CONSTRAINT grupo_pkey PRIMARY KEY (id);


--
-- TOC entry 2763 (class 2606 OID 1747362)
-- Name: permissao permissao_pkey; Type: CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.permissao
    ADD CONSTRAINT permissao_pkey PRIMARY KEY (id);


--
-- TOC entry 2765 (class 2606 OID 1747372)
-- Name: produto produto_pkey; Type: CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT produto_pkey PRIMARY KEY (id);


--
-- TOC entry 2767 (class 2606 OID 1747382)
-- Name: restaurante restaurante_pkey; Type: CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.restaurante
    ADD CONSTRAINT restaurante_pkey PRIMARY KEY (id);


--
-- TOC entry 2769 (class 2606 OID 1747396)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- TOC entry 2774 (class 2606 OID 1747420)
-- Name: restaurante fk76grk4roudh659skcgbnanthi; Type: FK CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.restaurante
    ADD CONSTRAINT fk76grk4roudh659skcgbnanthi FOREIGN KEY (cozinha_id) REFERENCES public.cozinha(id);


--
-- TOC entry 2776 (class 2606 OID 1747430)
-- Name: restaurante_forma_pagamento fk7aln770m80358y4olr03hyhh2; Type: FK CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.restaurante_forma_pagamento
    ADD CONSTRAINT fk7aln770m80358y4olr03hyhh2 FOREIGN KEY (forma_pagamento_id) REFERENCES public.forma_pagamento(id);


--
-- TOC entry 2777 (class 2606 OID 1747435)
-- Name: restaurante_forma_pagamento fka30vowfejemkw7whjvr8pryvj; Type: FK CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.restaurante_forma_pagamento
    ADD CONSTRAINT fka30vowfejemkw7whjvr8pryvj FOREIGN KEY (restaurante_id) REFERENCES public.restaurante(id);


--
-- TOC entry 2773 (class 2606 OID 1747415)
-- Name: produto fkb9jhjyghjcn25guim7q4pt8qx; Type: FK CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT fkb9jhjyghjcn25guim7q4pt8qx FOREIGN KEY (restaurante_id) REFERENCES public.restaurante(id);


--
-- TOC entry 2775 (class 2606 OID 1747425)
-- Name: restaurante fkbc0tm7hnvc96d8e7e2ulb05yw; Type: FK CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.restaurante
    ADD CONSTRAINT fkbc0tm7hnvc96d8e7e2ulb05yw FOREIGN KEY (endereco_cidade_id) REFERENCES public.cidade(id);


--
-- TOC entry 2779 (class 2606 OID 1747445)
-- Name: usuario_grupo fkdofo9es0esuiahyw2q467crxw; Type: FK CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.usuario_grupo
    ADD CONSTRAINT fkdofo9es0esuiahyw2q467crxw FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- TOC entry 2771 (class 2606 OID 1747405)
-- Name: grupo_permissao fkh21kiw0y0hxg6birmdf2ef6vy; Type: FK CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.grupo_permissao
    ADD CONSTRAINT fkh21kiw0y0hxg6birmdf2ef6vy FOREIGN KEY (permissao_id) REFERENCES public.permissao(id);


--
-- TOC entry 2778 (class 2606 OID 1747440)
-- Name: usuario_grupo fkk30suuy31cq5u36m9am4om9ju; Type: FK CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.usuario_grupo
    ADD CONSTRAINT fkk30suuy31cq5u36m9am4om9ju FOREIGN KEY (grupo_id) REFERENCES public.grupo(id);


--
-- TOC entry 2770 (class 2606 OID 1747400)
-- Name: cidade fkkworrwk40xj58kevvh3evi500; Type: FK CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.cidade
    ADD CONSTRAINT fkkworrwk40xj58kevvh3evi500 FOREIGN KEY (estado_id) REFERENCES public.estado(id);


--
-- TOC entry 2772 (class 2606 OID 1747410)
-- Name: grupo_permissao fkta4si8vh3f4jo3bsslvkscc2m; Type: FK CONSTRAINT; Schema: public; Owner: md2net
--

ALTER TABLE ONLY public.grupo_permissao
    ADD CONSTRAINT fkta4si8vh3f4jo3bsslvkscc2m FOREIGN KEY (grupo_id) REFERENCES public.grupo(id);


-- Completed on 2022-09-12 19:54:34

--
-- PostgreSQL database dump complete
--

