create table IF NOT EXISTS public.pedido (
  id bigint not null GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  subtotal numeric(10,2) not null,
  taxa_frete numeric(10,2) not null,
  valor_total numeric(10,2) not null,

  restaurante_id bigint not null,
  usuario_cliente_id bigint not null,
  forma_pagamento_id bigint not null,
  
  endereco_cidade_id bigint not null,
  endereco_cep character varying(9) not null,
  endereco_logradouro character varying(100) not null,
  endereco_numero character varying(20) not null,
  endereco_complemento character varying(60) null,
  endereco_bairro character varying(60) not null,
  
  status character varying(10) not null,
  data_criacao timestamp without time zone not null,
  data_confirmacao timestamp without time zone null,
  data_cancelamento timestamp without time zone null,
  data_entrega timestamp without time zone null,

  CONSTRAINT pedido_pkey PRIMARY KEY (id),

  constraint fk_pedido_restaurante foreign key (restaurante_id) references public.restaurante (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
  constraint fk_pedido_usuario_cliente foreign key (usuario_cliente_id) references public.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
  constraint fk_pedido_forma_pagamento foreign key (forma_pagamento_id) references public.forma_pagamento (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.pedido
    OWNER to md2net;

create table IF NOT EXISTS public.item_pedido (
  id bigint not null GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  quantidade bigint not null,
  preco_unitario numeric(10,2) not null,
  preco_total numeric(10,2) not null,
  observacao character varying(255) null,
  pedido_id bigint not null,
  produto_id bigint not null,
  
  CONSTRAINT item_pedido_pkey PRIMARY KEY (id, pedido_id, produto_id),

  constraint fk_item_pedido_pedido foreign key (pedido_id) references public.pedido (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
  constraint fk_item_pedido_produto foreign key (produto_id) references public.produto (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.item_pedido
    OWNER to md2net;